const copies = {
  ko: {"hint":"사업자 번호는 회원가입에 필수입니다. 가입 후 사업자 증빙을 제출해야 가격을 볼 수 있습니다.","help":"사업자등록증 또는 사업 운영 증빙자료를 제출하면 자동 승인되어 공급가격과 가격이 포함된 견적·Invoice를 이용할 수 있습니다. 증빙 제출 전에도 로그인, 상품 담기, 견적 문의는 가능합니다. 서류에서 불필요한 민감정보는 가려 주세요.","saved":"증빙 제출이 완료되었습니다. 가격을 확인할 수 있습니다.","required":"가격 열람을 위한 사업자 증빙 제출 안내"},
  en: {"hint":"A business registration number is required to sign up. Submit business evidence after registration to view prices.","help":"Submit a business registration certificate or evidence of business operations for automatic approval and access to wholesale prices, priced quotations and invoices. You can sign in, add products and request quotations before submitting evidence. Mask unnecessary sensitive information in documents.","saved":"Business evidence submitted. Prices are now available.","required":"Submit business evidence to view prices"},
  ja: {"hint":"会員登録には事業者登録番号が必要です。登録後、事業証明書類を提出すると価格を確認できます。","help":"事業者登録証または事業運営の証明書類を提出すると自動承認され、卸価格、価格付き見積書・請求書を利用できます。提出前でもログイン、商品追加、見積依頼は可能です。書類内の不要な機密情報は隠してください。","saved":"事業証明書類の提出が完了しました。価格を確認できます。","required":"価格確認のため事業証明書類を提出してください"},
  zh: {"hint":"注册账户必须填写企业注册号。注册后提交企业证明材料即可查看价格。","help":"提交企业登记证或经营证明材料后自动审核通过，即可查看批发价格、含价格的报价单和发票。提交前仍可登录、添加商品并申请报价。请遮盖文件中不必要的敏感信息。","saved":"企业证明材料已提交，现在可以查看价格。","required":"提交企业证明材料以查看价格"},
  vi: {"hint":"Cần có mã số doanh nghiệp để đăng ký. Sau khi đăng ký, hãy gửi chứng từ doanh nghiệp để xem giá.","help":"Gửi giấy đăng ký hoặc chứng từ hoạt động doanh nghiệp để được tự động duyệt và xem giá bán sỉ, báo giá có giá và hóa đơn. Trước khi gửi chứng từ, bạn vẫn có thể đăng nhập, thêm sản phẩm và yêu cầu báo giá. Hãy che thông tin nhạy cảm không cần thiết trong tài liệu.","saved":"Đã gửi chứng từ doanh nghiệp. Bạn có thể xem giá.","required":"Gửi chứng từ doanh nghiệp để xem giá"},
  id: {"hint":"Nomor registrasi usaha wajib diisi untuk mendaftar. Kirim bukti usaha setelah pendaftaran untuk melihat harga.","help":"Kirim sertifikat registrasi atau bukti kegiatan usaha untuk persetujuan otomatis dan akses harga grosir, penawaran dengan harga, serta faktur. Sebelum mengirim bukti, Anda tetap dapat masuk, menambahkan produk, dan meminta penawaran. Tutupi informasi sensitif yang tidak diperlukan pada dokumen.","saved":"Bukti usaha telah dikirim. Harga kini tersedia.","required":"Kirim bukti usaha untuk melihat harga"},
  th: {"hint":"ต้องกรอกเลขทะเบียนธุรกิจเพื่อสมัครสมาชิก หลังสมัครให้ส่งหลักฐานธุรกิจเพื่อดูราคา","help":"ส่งใบทะเบียนธุรกิจหรือหลักฐานการดำเนินธุรกิจเพื่อรับการอนุมัติอัตโนมัติและดูราคาขายส่ง ใบเสนอราคาที่มีราคา และใบแจ้งหนี้ ก่อนส่งหลักฐานยังสามารถเข้าสู่ระบบ เพิ่มสินค้า และขอใบเสนอราคาได้ กรุณาปิดบังข้อมูลอ่อนไหวที่ไม่จำเป็นในเอกสาร","saved":"ส่งหลักฐานธุรกิจเรียบร้อยแล้ว สามารถดูราคาได้","required":"ส่งหลักฐานธุรกิจเพื่อดูราคา"},
} as const;
export function businessAccessCopy(locale: string) {
  return copies[locale as keyof typeof copies] ?? copies.en;
}
