const copies = {
  ko: {optional:"선택",hint:"번호 없이도 가입할 수 있습니다. 사업자 번호를 등록하거나 증빙을 제출하면 자동 승인되어 가격이 표시됩니다.",help:"사업자 번호를 등록하거나 사업자 증빙을 제출하면 자동 승인되어 도매 가격과 가격이 포함된 견적·Invoice를 이용할 수 있습니다. 번호 없이도 로그인, 상품 담기, 견적 문의는 가능합니다. 서류에서 불필요한 민감정보는 가려 주세요.",saved:"등록이 완료되었습니다. 가격을 확인할 수 있습니다.",saveNumber:"사업자 번호 등록",required:"가격 열람을 위한 사업자 번호 등록 안내"},
  en: {optional:"optional",hint:"You can sign up without a number. Register a business number or submit business evidence to automatically enable prices.",help:"Register a business number or submit business evidence for automatic approval and access to wholesale prices, priced quotations and invoices. You can still sign in, add products and request quotations without a number. Mask unnecessary sensitive information in documents.",saved:"Registration complete. Prices are now available.",saveNumber:"Register business number",required:"Register a business number to view prices"},
  ja: {optional:"任意",hint:"番号なしでも登録できます。事業者登録番号の登録または証明書類の提出で自動承認され、価格を閲覧できます。",help:"事業者登録番号の登録または証明書類の提出で自動承認され、卸価格・価格付き見積書・請求書を利用できます。番号なしでもログイン、商品追加、見積依頼は可能です。書類の不要な機密情報は隠してください。",saved:"登録が完了しました。価格を閲覧できます。",saveNumber:"事業者登録番号を登録",required:"価格閲覧のため事業者登録番号を登録してください"},
  zh: {optional:"选填",hint:"不填写号码也可注册。登记企业注册号或提交企业证明后将自动批准并显示价格。",help:"登记企业注册号或提交企业证明即可自动批准，并查看批发价格、含价报价单和发票。未填写号码也可登录、添加商品及询价。请遮盖文件中不必要的敏感信息。",saved:"登记完成，现在可以查看价格。",saveNumber:"登记企业注册号",required:"登记企业注册号以查看价格"},
  vi: {optional:"không bắt buộc",hint:"Bạn có thể đăng ký mà không cần mã số. Đăng ký mã số doanh nghiệp hoặc gửi chứng từ để được tự động duyệt và xem giá.",help:"Đăng ký mã số doanh nghiệp hoặc gửi chứng từ để được tự động duyệt và xem giá bán sỉ, báo giá có giá và hóa đơn. Bạn vẫn có thể đăng nhập, thêm sản phẩm và yêu cầu báo giá khi chưa có mã số. Hãy che thông tin nhạy cảm không cần thiết trong chứng từ.",saved:"Đăng ký hoàn tất. Bạn có thể xem giá.",saveNumber:"Đăng ký mã số doanh nghiệp",required:"Đăng ký mã số doanh nghiệp để xem giá"},
  id: {optional:"opsional",hint:"Anda dapat mendaftar tanpa nomor. Daftarkan nomor registrasi usaha atau kirim bukti usaha untuk persetujuan otomatis dan akses harga.",help:"Daftarkan nomor registrasi usaha atau kirim bukti usaha untuk persetujuan otomatis dan akses harga grosir, penawaran dengan harga, serta faktur. Tanpa nomor, Anda tetap dapat masuk, menambahkan produk, dan meminta penawaran. Tutupi informasi sensitif yang tidak diperlukan pada dokumen.",saved:"Pendaftaran selesai. Harga kini tersedia.",saveNumber:"Daftarkan nomor registrasi usaha",required:"Daftarkan nomor registrasi usaha untuk melihat harga"},
  th: {optional:"ไม่บังคับ",hint:"สมัครได้โดยไม่กรอกเลขทะเบียนธุรกิจ ลงทะเบียนเลขทะเบียนธุรกิจหรือส่งเอกสารธุรกิจเพื่อรับการอนุมัติอัตโนมัติและดูราคา",help:"ลงทะเบียนเลขทะเบียนธุรกิจหรือส่งเอกสารธุรกิจเพื่อรับการอนุมัติอัตโนมัติและดูราคาขายส่ง ใบเสนอราคาที่ระบุราคา และใบแจ้งหนี้ หากยังไม่มีเลขทะเบียน คุณยังเข้าสู่ระบบ เพิ่มสินค้า และขอใบเสนอราคาได้ โปรดปิดบังข้อมูลอ่อนไหวที่ไม่จำเป็นในเอกสาร",saved:"ลงทะเบียนเรียบร้อยแล้ว สามารถดูราคาได้",saveNumber:"ลงทะเบียนเลขทะเบียนธุรกิจ",required:"ลงทะเบียนเลขทะเบียนธุรกิจเพื่อดูราคา"},
} as const;
export function businessAccessCopy(locale: string) {
  return copies[locale as keyof typeof copies] ?? copies.en;
}
