"use client";

import { businessAccessCopy } from "@/lib/auth/business-access-copy";
import { asianCopy } from "@/lib/asia-copy";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { businessDocumentCopy } from "@/lib/auth/business-document-copy";
export function BusinessDocumentForm({locale,submitted,businessNumber}:{locale:string;submitted:string|null;businessNumber:string}){
 const access=businessAccessCopy(locale);const t={...businessDocumentCopy(locale),help:access.help,saved:access.saved},router=useRouter();const [pending,setPending]=useState(false),[status,setStatus]=useState("");
 return <section className="mt-7 rounded-3xl border border-violet-200 bg-violet-50/40 p-4 sm:p-8"><h2 className="text-xl font-bold">{t.title}</h2><p className="mt-3 text-sm leading-7">{t.help}</p><p className="mt-4 text-sm">{submitted||t.none}</p>{submitted?<a href="/api/account/business-document" target="_blank" rel="noopener noreferrer" className="mt-2 inline-block text-sm text-violet-700 underline">{t.view}</a>:null}
 <form className="mt-5 space-y-4" onSubmit={async event=>{event.preventDefault();const form=event.currentTarget;setPending(true);setStatus("");try{const values=new FormData(form),file=values.get("document") as File;
const metadata={business_number:values.get("business_number"),website:values.get("website"),consent:values.get("consent")==="on",mime:file?.type,file_name:file?.name};
const send=async (body:object)=>{const res=await fetch("/api/account/business-document",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||"storage");return data;};
if ((event.nativeEvent as SubmitEvent).submitter?.getAttribute("value")==="number") {
 await send({business_number:values.get("business_number"),stage:"number"});setStatus(t.saved);router.refresh();return;
}
const prepared=await send({...metadata,stage:"prepare"});
const uploadBody=new FormData();uploadBody.append("cacheControl","3600");uploadBody.append("",file);
const uploaded=await fetch(prepared.url,{method:"PUT",headers:{"x-upsert":"false"},body:uploadBody});
if(!uploaded.ok){const data=await uploaded.json().catch(()=>({}));throw new Error(uploaded.status===413||/size|large|limit/i.test(data.message||data.error||"")?"size":"storage");}
await send({...metadata,stage:"complete",path:prepared.path});setStatus(t.saved);form.reset();router.refresh();}catch(error){const code=error instanceof Error?error.message:"storage";setStatus(locale==="ko"?({business_number:"실제 사업자 번호를 입력해 주세요. 반복 문자(dddd 등)는 사용할 수 없습니다.",consent:"증빙 열람 동의에 체크해 주세요.",website:"회사 홈페이지 주소를 확인해 주세요.",file_type:"PDF, JPG, PNG 파일을 선택해 주세요.",size:"저장소의 최대 파일 용량을 초과했습니다. 파일을 나누거나 압축해서 다시 제출해 주세요.",save:"파일은 업로드됐지만 제출 정보를 저장하지 못했습니다. 다시 제출해 주세요."} as Record<string,string>)[code]||"업로드하지 못했습니다. 잠시 후 다시 시도해 주세요.":t.error);}finally{setPending(false);}}}>
 <fieldset disabled={pending} className="space-y-4"><label className="block text-sm font-medium">{asianCopy(locale)?.businessNumber ?? (locale === "ko" ? "사업자 번호 / 현지 사업자 등록번호" : "Business / local registration number")}<input name="business_number" required minLength={3} maxLength={50} defaultValue={businessNumber} className="mt-2 block w-full rounded-xl border bg-white p-3"/></label><label className="block text-sm font-medium">{t.file}<input type="file" name="document" required accept="application/pdf,image/jpeg,image/png" className="mt-2 block w-full rounded-xl border bg-white p-3"/></label><p className="text-xs text-zinc-500">{t.format}</p><label className="block text-sm font-medium">{t.website}<input type="url" name="website" maxLength={500} placeholder="https://" className="mt-2 block w-full rounded-xl border bg-white p-3"/></label><label className="flex items-start gap-3 text-sm"><input type="checkbox" name="consent" required className="mt-1"/>{t.consent}</label><button type="submit" name="action" value="number" formNoValidate className="block w-full rounded-xl border border-violet-700 sm:mr-3 sm:inline-block sm:w-auto px-5 py-3 font-semibold text-violet-700">{access.saveNumber}</button><button type="submit" name="action" value="document" className="mt-3 block w-full rounded-xl bg-violet-700 sm:mt-0 sm:inline-block sm:w-auto px-5 py-3 font-semibold text-white">{pending?t.pending:t.upload}</button></fieldset><a href={`/${locale}/wholesale-inquiry`} className="inline-block text-sm text-violet-700 underline">{asianCopy(locale)?.quoteRequest ?? (locale === "ko" ? "가격 열람 전에도 견적 문의하기" : "Request a quotation while verification is pending")}</a>{status?<p role="status" className="text-sm">{status}</p>:null}</form></section>;
}
