"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { businessDocumentCopy } from "@/lib/auth/business-document-copy";
export function BusinessDocumentForm({locale,submitted,businessNumber}:{locale:string;submitted:string|null;businessNumber:string}){
 const t=businessDocumentCopy(locale),router=useRouter();const [pending,setPending]=useState(false),[status,setStatus]=useState("");
 return <section className="mt-7 rounded-3xl border border-violet-200 bg-violet-50/40 p-6 sm:p-8"><h2 className="text-xl font-bold">{t.title}</h2><p className="mt-3 text-sm leading-7">{t.help}</p><p className="mt-4 text-sm">{submitted||t.none}</p>{submitted?<a href="/api/account/business-document" target="_blank" rel="noopener noreferrer" className="mt-2 inline-block text-sm text-violet-700 underline">{t.view}</a>:null}
 <form className="mt-5 space-y-4" onSubmit={async event=>{event.preventDefault();const form=event.currentTarget;setPending(true);setStatus("");try{const res=await fetch("/api/account/business-document",{method:"POST",body:new FormData(form)});if(!res.ok)throw Error();setStatus(t.saved);form.reset();router.refresh();}catch{setStatus(t.error);}finally{setPending(false);}}}>
 <fieldset disabled={pending} className="space-y-4"><label className="block text-sm font-medium">{locale === "ko" ? "사업자 번호 / 현지 사업자 등록번호" : "Business / local registration number"}<input name="business_number" required minLength={3} maxLength={50} defaultValue={businessNumber} className="mt-2 block w-full rounded-xl border bg-white p-3"/></label><label className="block text-sm font-medium">{t.file}<input type="file" name="document" required accept="application/pdf,image/jpeg,image/png" className="mt-2 block w-full rounded-xl border bg-white p-3"/></label><p className="text-xs text-zinc-500">{t.format}</p><label className="block text-sm font-medium">{t.website}<input type="url" name="website" maxLength={500} placeholder="https://" className="mt-2 block w-full rounded-xl border bg-white p-3"/></label><label className="flex items-start gap-3 text-sm"><input type="checkbox" name="consent" required className="mt-1"/>{t.consent}</label><button className="rounded-xl bg-violet-700 px-5 py-3 font-semibold text-white">{pending?t.pending:t.upload}</button></fieldset><a href={`/${locale}/wholesale-inquiry`} className="inline-block text-sm text-violet-700 underline">{locale === "ko" ? "가격 열람 전에도 견적 문의하기" : "Request a quotation while verification is pending"}</a>{status?<p role="status" className="text-sm">{status}</p>:null}</form></section>;
}
