"use client";
import { businessAccessCopy } from "@/lib/auth/business-access-copy";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import { asianCopy } from "@/lib/asia-copy";
type Item={id:string;kind:string;detail:string;href:string;status?:string};
type Feed={userId:string;notifications:Item[]};
export function CustomerNotifications({locale}:{locale:string}){
 const ko=locale==="ko",ja=locale==="ja",zh=locale==="zh";
 const asian = asianCopy(locale);
 const labels=asian ?? (ko?{title:"내 알림",all:"모두 읽음",empty:"새로운 알림이 없습니다.",error:"알림을 불러오지 못했습니다.",approved:"사업자 승인 완료 · 공급가 열람 가능",review:"사업자 증빙 제출 완료 · 검토 대기",order:"주문·견적 상태",quoteRead:"담당자가 견적 요청을 확인했습니다."}:ja?{title:"通知",all:"すべて既読",empty:"通知はありません。",error:"通知を読み込めませんでした。",approved:"事業者承認完了",review:"事業者書類の審査待ち",order:"注文・見積状況",quoteRead:"担当者が見積依頼を確認しました。"}:zh?{title:"我的通知",all:"全部已读",empty:"暂无通知。",error:"无法加载通知。",approved:"企业审核已通过",review:"企业资料等待审核",order:"订单与报价状态",quoteRead:"工作人员已查看报价请求。"}:{title:"My notifications",all:"Mark all read",empty:"No notifications yet.",error:"Unable to load notifications.",approved:"Business approved · wholesale prices available",review:"Business document received · awaiting review",order:"Order / quotation status",quoteRead:"Your quotation request has been reviewed."});
 const [feed,setFeed]=useState<Feed|null>(null),[read,setRead]=useState<string[]>([]),[open,setOpen]=useState(false),[error,setError]=useState(false);const panel=useRef<HTMLDivElement>(null);
 useEffect(()=>{let stopped=false;const controller=new AbortController();const refresh=async()=>{if(document.hidden)return;try{const res=await fetch("/api/account/notifications",{cache:"no-store",signal:controller.signal});if(!res.ok)throw Error();const data:Feed=await res.json();if(stopped)return;let ids:string[]=[];try{const saved=JSON.parse(localStorage.getItem(`hmt-customer-notifications:${data.userId}`)||"[]");if(Array.isArray(saved))ids=saved.filter(x=>typeof x==="string");}catch{}setFeed(data);setRead(ids);setError(false);}catch{if(!stopped)setError(true);}};void refresh();const timer=setInterval(()=>void refresh(),30000);window.addEventListener("focus",refresh);document.addEventListener("visibilitychange",refresh);window.addEventListener("hmt-notifications-read",refresh);window.addEventListener("hmt-notifications-read",refresh);return()=>{stopped=true;controller.abort();clearInterval(timer);window.removeEventListener("focus",refresh);document.removeEventListener("visibilitychange",refresh);window.removeEventListener("hmt-notifications-read",refresh);window.removeEventListener("hmt-notifications-read",refresh);};},[]);
 useEffect(()=>{if(!open)return;const close=(event:PointerEvent)=>{if(!panel.current?.contains(event.target as Node))setOpen(false);};const escape=(event:KeyboardEvent)=>{if(event.key==="Escape")setOpen(false);};document.addEventListener("pointerdown",close);document.addEventListener("keydown",escape);return()=>{document.removeEventListener("pointerdown",close);document.removeEventListener("keydown",escape);};},[open]);
 const mark=(ids:string[])=>{const next=[...new Set([...read,...ids])].slice(-2000);setRead(next);try{localStorage.setItem(`hmt-customer-notifications:${feed?.userId}`,JSON.stringify(next));}catch{}};
 const unread=feed?.notifications.filter(x=>!read.includes(x.id)).length||0;
 return <div ref={panel} className="relative"><button type="button" aria-label={`${labels.title}${unread?` (${unread})`:""}`} aria-expanded={open} onClick={()=>setOpen(!open)} className="relative flex h-10 w-10 items-center justify-center rounded-full border border-violet-200 text-violet-700 hover:bg-violet-50"><svg viewBox="0 0 24 24" className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d="M18 8a6 6 0 00-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4" strokeLinecap="round"/></svg>{unread>0&&<span className="absolute -right-1 -top-1 rounded-full bg-pink-500 px-1.5 text-[10px] font-bold text-white">{unread>99?"99+":unread}</span>}</button>{open&&<section aria-label={labels.title} className="absolute right-0 top-12 z-[100] w-[min(22rem,calc(100vw-2rem))] overflow-hidden rounded-2xl border bg-white shadow-xl"><div className="flex justify-between border-b p-4"><h2 className="font-bold">{labels.title}</h2><button type="button" onClick={()=>mark(feed?.notifications.map(x=>x.id)||[])} className="text-xs text-violet-700">{labels.all}</button></div>{error?<p role="status" className="p-4 text-sm">{labels.error}</p>:!feed?.notifications.length?<p className="p-4 text-sm text-zinc-500">{labels.empty}</p>:<ul className="max-h-[55vh] overflow-y-auto">{feed.notifications.map(item=><li key={item.id}><Link prefetch={false} href={`/${locale}/account/notifications?id=${encodeURIComponent(item.id)}`} onClick={()=>setOpen(false)} className={`block border-b p-4 hover:bg-violet-50 ${read.includes(item.id)?"":"bg-violet-50/60"}`}><p className="text-sm font-semibold">{item.kind==="businessRequired"?businessAccessCopy(locale).required:labels[item.kind as keyof typeof labels]||labels.order}</p><p className="mt-1 text-xs text-zinc-500">{item.detail}{item.status?` · ${item.status}`:""}</p></Link></li>)}</ul>}<Link href={`/${locale}/account/notifications`} onClick={()=>setOpen(false)} className="block border-t p-4 text-center text-sm font-semibold text-violet-700">{asian?.viewAll ?? (ko?"알림 전체 보기":ja?"すべてのお知らせ":zh?"查看全部通知":"View all notifications")} →</Link></section>}</div>;
}
