"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import { asianCopy } from "@/lib/asia-copy";
type Item={id:string;kind:string;detail:string;href:string;status?:string};
type Feed={userId:string;notifications:Item[]};
export function NotificationInbox({locale}:{locale:string}){
 const ko=locale==="ko",ja=locale==="ja",zh=locale==="zh";
 const asian = asianCopy(locale);
 const ui=asian ?? (ko?{title:"내 알림",intro:"회원 승인과 주문·견적 소식을 자세히 확인하세요.",all:"모두 읽음",empty:"아직 알림이 없습니다.",error:"알림을 불러오지 못했습니다.",retry:"다시 시도",action:"관련 화면으로 이동",account:"마이페이지",loading:"알림을 불러오는 중…",read:"읽음",unread:"새 알림"}:ja?{title:"お知らせ",intro:"承認・注文・見積のお知らせを確認できます。",all:"すべて既読",empty:"お知らせはありません。",error:"読み込めませんでした。",retry:"再試行",action:"関連ページへ",account:"マイページ",loading:"読み込み中…",read:"既読",unread:"未読"}:zh?{title:"我的通知",intro:"查看企业审核、订单和报价通知。",all:"全部已读",empty:"暂无通知。",error:"无法加载通知。",retry:"重试",action:"查看相关页面",account:"我的账户",loading:"正在加载…",read:"已读",unread:"未读"}:{title:"My notifications",intro:"Read updates about business approval, orders and quotations.",all:"Mark all read",empty:"No notifications yet.",error:"Unable to load notifications.",retry:"Try again",action:"Open related page",account:"My account",loading:"Loading notifications…",read:"Read",unread:"New"});
 const text=(kind:string)=>{
  if (asian) { const entries: Record<string, [string,string]> = { businessRequired: [asian.businessRequired, asian.businessRequiredBody], approved: [asian.approved,asian.approvedBody], review:[asian.review,asian.reviewBody], quoteRead:[asian.quoteRead,asian.quoteReadBody], order:[asian.order,asian.orderBody] }; return entries[kind] ?? entries.order; }
  const content:Record<string,[string,string]>=ko?{
   businessRequired:["가격 조회를 위한 사업자 증빙 안내","공급가와 가격이 포함된 견적·인보이스를 이용하려면 사업자등록증, 해외 사업자등록·사업허가증 또는 사업 운영을 확인할 수 있는 증빙자료를 제출하고 관리자 승인을 받아 주세요. 로그인과 가격 없는 도매 문의는 승인 전에도 가능합니다. 마이페이지의 사업자 증빙에서 사업자 번호와 자료를 제출해 주세요. 불필요한 주민번호 등 민감정보는 가려 주세요."],
   approved:["사업자 승인이 완료되었습니다","이제 공급가를 확인하고 가격이 포함된 견적과 인보이스를 이용할 수 있습니다. 상품을 선택하여 견적 요청을 준비해 주세요."],
   review:["사업자 증빙이 접수되었습니다","관리자가 제출하신 사업자 증빙을 확인 중입니다. 승인이 완료되면 공급가를 확인할 수 있습니다. 승인 전에도 도매 문의를 남길 수 있습니다."],
   quoteRead:["담당자가 견적 요청을 확인했습니다","담당자가 견적 요청을 열람했습니다. 재고와 거래 조건을 확인한 뒤 안내드립니다. 관련 화면에서 요청 상품과 견적 상태를 확인해 주세요."],
   order:["주문·견적 상태 안내","아래 요청 번호와 현재 처리 상태를 확인해 주세요. 관련 화면에서 요청하신 상품과 상세 내역을 확인할 수 있습니다."]
  }:ja?{businessRequired:["価格閲覧には事業証明が必要です","事業者登録証または事業運営を証明する資料をマイページから提出し、管理者の承認を受けてください。承認前もログインと価格なしのお問い合わせは可能です。不要な個人情報は隠してください。"],approved:["事業者承認完了","卸価格と価格を含む見積・請求書をご利用いただけます。"],review:["事業証明を受け付けました","管理者が書類を確認中です。承認後に卸価格を閲覧できます。"],quoteRead:["見積依頼が確認されました","担当者が依頼を確認しました。関連ページで詳細をご確認ください。"],order:["注文・見積の状況","依頼番号と現在の処理状況をご確認ください。"]}:zh?{businessRequired:["查看价格前需提交企业证明","请在我的账户中提交营业执照或其他经营证明，并等待管理员审核。审核前仍可登录并提交不含价格的询价。请遮盖不必要的个人敏感信息。"],approved:["企业审核已通过","现在可以查看批发价格及含价格的报价和发票。"],review:["企业证明已收到","管理员正在审核材料，审核通过后可以查看批发价格。"],quoteRead:["报价请求已被查看","负责人已查看您的请求，请在相关页面查看详细信息。"],order:["订单与报价状态","请查看请求编号和当前处理状态。"]}:{businessRequired:["Business evidence required to view prices","Submit a registration certificate, business licence or other evidence of business operations in My account and receive administrator approval to view supply prices and priced quotations or invoices. You can still sign in and send price-free wholesale inquiries before approval. Redact unnecessary sensitive personal information."],approved:["Business approval complete","You can now view supply prices and use priced quotations and invoices."],review:["Business evidence received","Your evidence is awaiting administrator review. Supply prices become available after approval. You can send wholesale inquiries while waiting."],quoteRead:["Your quotation has been reviewed","Our team has opened your quotation request. Open the related page to check its details."],order:["Order / quotation update","Check the request number and current processing status below. Open the related page for its details."]};
  return content[kind]||content.order;
 };
 const [feed,setFeed]=useState<Feed|null>(null),[read,setRead]=useState<string[]>([]),[selected,setSelected]=useState(""),[error,setError]=useState(false),[retry,setRetry]=useState(0);
 const mark=(ids:string[],owner:string)=>{let saved:string[]=[];try{saved=JSON.parse(localStorage.getItem(`hmt-customer-notifications:${owner}`)||"[]");if(!Array.isArray(saved))saved=[];}catch{}const next=[...new Set([...saved,...ids])].filter(x=>typeof x==="string").slice(-2000);setRead(next);try{localStorage.setItem(`hmt-customer-notifications:${owner}`,JSON.stringify(next));window.dispatchEvent(new Event("hmt-notifications-read"));}catch{}};
 useEffect(()=>{const controller=new AbortController();fetch("/api/account/notifications",{cache:"no-store",signal:controller.signal}).then(async response=>{if(!response.ok)throw Error();return response.json() as Promise<Feed>;}).then(data=>{if(controller.signal.aborted)return;setFeed(data);let saved:string[]=[];try{saved=JSON.parse(localStorage.getItem(`hmt-customer-notifications:${data.userId}`)||"[]");if(!Array.isArray(saved))saved=[];}catch{}setRead(saved);const requested=new URLSearchParams(window.location.search).get("id");const item=data.notifications.find(x=>x.id===requested);if(item){setSelected(item.id);mark([item.id],data.userId);}}).catch(()=>{if(!controller.signal.aborted)setError(true);});return()=>controller.abort();},[retry]);
 const current=feed?.notifications.find(x=>x.id===selected);
 return <main className="mx-auto max-w-6xl px-4 py-10 sm:py-14"><div className="mb-7 rounded-3xl border border-pink-100 bg-gradient-to-br from-pink-50 via-white to-violet-50 p-7 sm:p-10"><p className="text-xs font-bold tracking-[.2em] text-pink-600">HMT KOREA</p><h1 className="mt-3 text-3xl font-bold">{ui.title}</h1><p className="mt-3 text-zinc-600">{ui.intro}</p><Link href={`/${locale}/account`} className="mt-5 inline-block text-sm font-semibold text-violet-700">← {ui.account}</Link></div>{error?<div role="alert" className="rounded-2xl border p-6">{ui.error}<button onClick={()=>{setError(false);setRetry(x=>x+1);}} className="ml-4 text-violet-700 underline">{ui.retry}</button></div>:!feed?<p role="status">{ui.loading}</p>:<div className="grid gap-6 lg:grid-cols-[320px_1fr]"><section className="overflow-hidden rounded-2xl border bg-white"><div className="flex items-center justify-between border-b p-4"><h2 className="font-semibold">{ui.title}</h2><button onClick={()=>mark(feed.notifications.map(x=>x.id),feed.userId)} className="text-xs text-violet-700">{ui.all}</button></div>{!feed.notifications.length?<p className="p-6 text-sm text-zinc-500">{ui.empty}</p>:<ul className="max-h-[60vh] overflow-y-auto">{feed.notifications.map(item=><li key={item.id}><button type="button" aria-pressed={current?.id===item.id} onClick={()=>{setSelected(item.id);mark([item.id],feed.userId);}} className={`w-full border-b p-5 text-left hover:bg-violet-50 ${current?.id===item.id?"bg-violet-50":""}`}><span className={`text-xs ${read.includes(item.id)?"text-zinc-400":"font-bold text-pink-600"}`}>{read.includes(item.id)?ui.read:ui.unread}</span><p className="mt-2 text-sm font-semibold leading-6">{text(item.kind)[0]}</p>{item.detail&&<p className="mt-2 break-all text-xs text-zinc-500">{item.detail}</p>}</button></li>)}</ul>}</section><article className="min-h-72 rounded-2xl border bg-white p-6 sm:p-9" aria-live="polite">{current?<><p className="text-xs font-semibold text-violet-700">{ui.read}</p><h2 className="mt-4 text-2xl font-bold leading-snug">{text(current.kind)[0]}</h2><p className="mt-6 whitespace-pre-line text-base leading-8 text-zinc-600">{text(current.kind)[1]}</p>{current.detail&&<p className="mt-6 break-all rounded-xl bg-zinc-50 p-4 font-mono text-sm">{current.detail}{current.status?` · ${current.status}`:""}</p>}<Link href={`/${locale}${current.href}`} className="mt-8 inline-block rounded-xl bg-violet-700 px-5 py-3 text-sm font-semibold text-white">{ui.action} →</Link></>:<p className="text-zinc-500">{feed.notifications.length?ui.intro:ui.empty}</p>}</article></div>}</main>;
}
